name: Publish to PyPI

on:
  push:
    branches:
      - main  # Change this to your main branch name
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you want to use

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust this as needed

      - name: Run unit tests
        run: python -m unittest discover

      - name: Install setuptools and wheel
        run: pip install setuptools wheel

      - name: Build source distribution
        run: python setup.py sdist

      - name: Build wheel distribution
        run: python setup.py bdist_wheel

      - name: Set Environment Variables
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            export TWINE_UPLOAD_CMD="upload dist/*"
            export TWINE_USERNAME=${{ env.PYPI_USERNAME }}
            export TWINE_PASSWORD=${{ secrets.PYPI_PASSWORD }}
          elif [[ ${{ github.ref }} == 'refs/heads/dev/'* ]]; then
            export TWINE_UPLOAD_CMD="--repository-url https://test.pypi.org/legacy/ dist/*"
            export TWINE_USERNAME=${{ env.TESTPYPI_USERNAME }}
            export TWINE_PASSWORD=${{ secrets.TESTPYPI_PASSWORD }}
          else
            echo "Unknown branch"
          fi

      - name: Upload to PyPI
#        if: success()
        run: |
          pip install twine
          echo "Uploading module"
          twine upload  
#          twine upload dist/*
#          twine upload --repository-url https://test.pypi.org/legacy/ dist/*