name: Publish to PyPI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you want to use

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust this as needed

      - name: Run unit tests
        run: python -m unittest discover

      - name: Install setuptools and wheel
        run: pip install setuptools wheel

      - name: Build source distribution
        run: python setup.py sdist

      - name: Build wheel distribution
        run: python setup.py bdist_wheel

#      - name: Upload to PyPI
#        if: success()
#        run: |
#          pip install twine
#          twine upload dist/*
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
